name: Tartelet
options:
  bundleIdPrefix: dk.shape
  developmentLanguage: en
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: xcconfigs/General.xcconfig
  Release: xcconfigs/General.xcconfig
targets:
  Tartelet:
    type: application
    platform: macOS
    sources: [Tartelet]
    postCompileScripts:
    - name: Run SwiftLint
      path: scripts/swiftlint.sh
      basedOnDependencyAnalysis: false
    dependencies:
      - package: FileSystem
        products: [FileSystemData, FileSystemDomain]
      - package: GitHub
        products: [GitHubData, GitHubDomain]
      - package: Keychain
        products: Keychain
      - package: Logging
        products: [LoggingData, LoggingDomain]
      - package: MenuBar
        products: MenuBar
      - package: Networking
        products: [NetworkingData, NetworkingDomain]
      - package: Settings
        products: [SettingsData, SettingsDomain, SettingsUI]
      - package: Shell
        products: [ShellData, ShellDomain]
      - package: VirtualMachine
        products: [VirtualMachineData, VirtualMachineDomain]
localPackages:
  - Packages/FileSystem
  - Packages/GitHub
  - Packages/Keychain
  - Packages/Logging
  - Packages/MenuBar
  - Packages/Networking
  - Packages/Settings
  - Packages/Shell
  - Packages/VirtualMachine
