name: Tartelet
options:
  bundleIdPrefix: dk.shape
  developmentLanguage: en
configs:
  Debug: debug
  Release: release
configFiles:
  Debug: xcconfigs/General.xcconfig
  Release: xcconfigs/General.xcconfig
targets:
  Tartelet:
    type: application
    platform: macOS
    sources: [Tartelet]
    postCompileScripts:
    - name: Run SwiftLint
      path: scripts/swiftlint.sh
      basedOnDependencyAnalysis: false
    dependencies:
      - package: FileSystem
        product: FileSystemData
      - package: FileSystem
        product: FileSystemDomain
      - package: GitHub
        product: GitHubData
      - package: GitHub
        product: GitHubDomain
      - package: Keychain
        product: Keychain
      - package: Logging
        product: LoggingData
      - package: Logging
        product: LoggingDomain
      - package: MenuBar
        product: MenuBar
      - package: Networking
        product: NetworkingData
      - package: Networking
        product: NetworkingDomain
      - package: Settings
        product: SettingsData
      - package: Settings
        product: SettingsDomain
      - package: Settings
        product: SettingsUI
      - package: Shell
        product: Shell
      - package: VirtualMachine
        product: VirtualMachineData
      - package: VirtualMachine
        product: VirtualMachineDomain
localPackages:
  - Packages/FileSystem
  - Packages/GitHub
  - Packages/Keychain
  - Packages/Logging
  - Packages/MenuBar
  - Packages/Networking
  - Packages/Settings
  - Packages/Shell
  - Packages/VirtualMachine
