name: Build
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'Tartelet/**'
      - 'Packages/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
    - name: Add SSH Key
      run: ssh-keygen -t ed25519 -C "tartelet@shape.dk" -P "" -f "$HOME/.ssh/id_rsa"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install xcodegen
      run: brew install xcodegen
    - name: Generate .xcodeproj
      run: xcodegen
    - name: Build
      run: xcodebuild build -scheme Tartelet -destination 'generic/platform=macOS'
