name: Build
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'Tartelet/**'
      - 'Packages/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install xcodegen
      run: brew install xcodegen
    - name: Generate .xcodeproj
      run: xcodegen
    - name: Build
      run: xcodebuild build-for-testing -scheme Tartelet -destination 'generic/platform=macOS'
