name: SwiftLint
on:
  workflow_dispatch: {}
  pull_request: {}
jobs:
  SwiftLint:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: SwiftLint
        run: swiftlint --quiet --reporter github-actions-logging
